config/routes.rb
Rails.application.routes.draw do
  #get 'favorites/index'

  post '/rate' => 'rater#create', :as => 'rate'
  get 'users/show' => 'users#show'
  get 'users/profile/:id' => 'users#profile'
  resources :favorites
  #get 'users/edit' => 'users#edit'
  #patch 'users/update' => 'users#update'
  resources :genres
  resources :playlists
  resources :albums
  resources :posts
  resources :songs
  resources :artists
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'home_page/Index'

  devise_for :users
  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :artist
  has_many :songs
  belongs_to :user
  belongs_to :genre
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :songs
  has_many :albums
  belongs_to :user
  belongs_to :genre
  #letsrate_rateable "quality"
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :song
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :albums
  has_many :artists
  has_many :songs
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/playlist.rb
class Playlist < ApplicationRecord
  has_many :songs
  belongs_to :user
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :artist
  belongs_to :user
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :album
  belongs_to :artist
  belongs_to :user
  belongs_to :genre
  ratyrate_rateable 'song'
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :artists
  has_many :albums
  has_many :songs
  has_many :posts
  has_many :favorites
  ratyrate_rater
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/controllers/home_page_controller.rb
require 'api_consuming'
class HomePageController < ApplicationController
  before_action :authenticate_user!
  def Index
    @posts = Post.last(10)
    #@arturo = api_consult 'https://www.youtube.com/results?search_query=hola'
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/home_page_helper.rb
module HomePageHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home_page/Index.html.erb
<div class="container">
      <div class="bg-faded p-4 my-4">
        <!-- Welcome Message -->
        <div class="text-center mt-4">
          <div class="text-heading text-muted text-lg">Welcome To</div>
          <h1 class="my-2">Spotify2 <%= image_tag('rails.png', height: '50', width: '50') %></h1>
          <div class="text-heading text-muted text-lg">By
            <strong>Grupo 10</strong>
          </div>
        </div>
      </div>

      <div class="bg-faded p-4 my-4">
        <hr class="divider">
        <h2 class="text-center text-lg text-uppercase my-0">The website
          <strong>with your music</strong>
        </h2>
        <hr class="divider">
        <h2 class="text-center text-lg text-uppercase my-0">Choose your option
          <strong>and Explore</strong></h2>
        <hr class="divider">

  <div class="bg-faded p-4 my-4">
    <div class="left-float">
      <div class="row">
      <div class="column">
        <%= link_to image_tag( asset_path("Home/pic01.jpg"), width:'480', height:'270', alt:"hola"),songs_path %>
      </div>
      <%= link_to '<h2 class="text-center text-lg text-uppercase my-0">Songs</h2>'.html_safe, songs_path %>

      <div class="column">
        <%= link_to image_tag(asset_path("Home/pic03.jpg"), width:'480', height:'270'), albums_path %>
      </div>
        <%= link_to '<h2 class="text-center text-lg text-uppercase my-0">Albums</h2>'.html_safe, albums_path %>
      <div class="column">
        <%= link_to image_tag(asset_path("Home/pic05.jpg"), width:'480', height:'270'), playlists_path %>
      </div>
        <%= link_to '<h2 class="text-center text-lg text-uppercase my-0">Playlists</h2>'.html_safe, playlists_path %>
        <hr class="divider">
      </div>

    </div>
    <div class="left-float">
      <div class="row">
      <div class="column">
        <%= link_to image_tag(asset_path("Home/pic02.jpg"), width:'480', height:'270'), artists_path %>
      </div>
        <%= link_to '<h2 class="text-center text-lg text-uppercase my-0">Artists</h2>'.html_safe, artists_path %>
      <div class="column">
        <%= link_to image_tag(asset_path("Home/pic04.jpg"), width:'480', height:'270'), posts_path %>
      </div>
        <%= link_to '<h2 class="text-center text-lg text-uppercase my-0">News</h2>'.html_safe, posts_path %>
      <div class="column">
          <%= link_to image_tag(asset_path("Home/pic06.jpg"), width:'480', height:'270'), genres_path%>
      </div>
          <%= link_to '<h2 class="text-center text-lg text-uppercase my-0">Genre</h2>'.html_safe, genres_path %>
          <hr class="divider">
     </div>
    </div>
  </div>
</div>


      <div class="bg-faded p-4 my-4">

      <div class="container">
        <hr class="divider">
        <h2 class="text-center text-lg text-uppercase my-0">Some
          <strong>interesting news</strong>
        </h2>
        <table class="table table-bordered">
          <thead>
            <tr>
              <th><h2>News</h2></th>
            </tr>
          </thead>

          <tbody>
          <% @posts.each do |post| %>
              <tr>
                <td>
                  <h4><strong>Title: <%= link_to post.title, post %></strong></h4>
                  <h4>Content: <%= post.body %></h4>
                  <h5>Related artist: <%= link_to "#{post.artist.name}", post.artist %></h5>
                  <h5>Created by: <%= link_to "#{post.user.email}", "/users/profile/#{post.user.id}" %></h5>
                  <% if post.user == current_user %>
                      <%= link_to 'Edit', edit_post_path(post) %>
                      <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
                  <% end %>
                </td>
              </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>


  </div>


    <!-- /.container -->