config/routes.rb
Rails.application.routes.draw do
  #get 'favorites/index'

  post '/rate' => 'rater#create', :as => 'rate'
  get 'users/show' => 'users#show'
  get 'users/profile/:id' => 'users#profile'
  resources :favorites
  #get 'users/edit' => 'users#edit'
  #patch 'users/update' => 'users#update'
  resources :genres
  resources :playlists
  resources :albums
  resources :posts
  resources :songs
  resources :artists
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'home_page/Index'

  devise_for :users
  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :artist
  has_many :songs
  belongs_to :user
  belongs_to :genre
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :songs
  has_many :albums
  belongs_to :user
  belongs_to :genre
  #letsrate_rateable "quality"
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :song
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :albums
  has_many :artists
  has_many :songs
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/playlist.rb
class Playlist < ApplicationRecord
  has_many :songs
  belongs_to :user
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :artist
  belongs_to :user
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :album
  belongs_to :artist
  belongs_to :user
  belongs_to :genre
  ratyrate_rateable 'song'
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :artists
  has_many :albums
  has_many :songs
  has_many :posts
  has_many :favorites
  ratyrate_rater
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_artist, only: [:show, :edit, :update, :destroy]

  # GET /artists
  # GET /artists.json
  def index
    @artists = Artist.all
  end

  # GET /artists/1
  # GET /artists/1.json
  def show
    @posts = Post.where(artist_id:  @artist.id)
    @albums = Album.where(:artist_id => @artist.id)
  end

  # GET /artists/new
  def new
    @artist = Artist.new
  end

  # GET /artists/1/edit
  def edit
  end

  # POST /artists
  # POST /artists.json
  def create
    artist_params2 = {}
    artist_params.each do |key, value|
      artist_params2[key] = value if key != :genre
    end
    artist_params2[:genre]= Genre.find(artist_params[:genre])
    @artist = Artist.new(artist_params2)
    @artist.user = current_user

    respond_to do |format|
      if @artist.save
        format.html { redirect_to @artist, notice: 'Artist was successfully created.' }
        format.json { render :show, status: :created, location: @artist }
      else
        format.html { render :new }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artists/1
  # PATCH/PUT /artists/1.json
  def update
    respond_to do |format|
      artist_params2 = {}
      artist_params.each do |key, value|
        artist_params2[key] = value if key != :genre
      end
      artist_params2[:genre]= Genre.find(artist_params[:genre])
      if @artist.update(artist_params2)
        format.html { redirect_to @artist, notice: 'Artist was successfully updated.' }
        format.json { render :show, status: :ok, location: @artist }
      else
        format.html { render :edit }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artists/1
  # DELETE /artists/1.json
  def destroy
    @artist.destroy
    respond_to do |format|
      format.html { redirect_to artists_url, notice: 'Artist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artist
      @artist = Artist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def artist_params
      params.require(:artist).permit(:name, :description, :genre, :nationality, :active_time, :image)
    end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/home_page_helper.rb
module HomePageHelper
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/artists/_form.html.erb
<div class="container">
<%= form_with(model: artist, local: true, html: { multipart: true }) do |form| %>
  <% if artist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(artist.errors.count, "error") %> prohibited this artist from being saved:</h2>

      <ul>
      <% artist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :artist_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :artist_description %>
  </div>

  <div class="field">
    <%= form.label :genre %>
    <%= form.collection_select :genre, Genre.order(:name),:id,:name, include_blank: true %>
    <% #form.genre = Genre.find(form.genre) %>
  </div>

  <div class="field">
    <%= form.label :nationality %>
    <%= form.text_field :nationality, id: :artist_nationality %>
  </div>

  <div class="field">
    <%= form.label :active_time %>
    <%= form.text_field :active_time, id: :artist_active_time %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</div>

app/views/artists/edit.html.erb
<h1>Editing Artist</h1>

<%= render 'form', artist: @artist %>

<%= link_to 'Show', @artist %> |
<%= link_to 'Back', artists_path %>

app/views/artists/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="bg-faded p-4 my-4">
    <!-- Welcome Message -->
    <div class="text-center mt-4">
      <h1 class="my-2">Artists <%= image_tag('Artists/img1.jpg', height:'72', width:'72') %></h1>
        <hr class="divider">
        <h2 class="text-center text-lg text-uppercase my-0">If you want, you can:
        <strong><%= link_to 'Create Artist', new_artist_path %></strong>
        </h2>
      </div>
    </div>
  </div>
  <hr class="divider">
  <h2 class="text-center text-lg text-uppercase my-0">Or
  <strong>Explore</strong>
  </h2>
  <hr class="divider">

  <div id="gallery">
    <ul id="grid">
      <% @artists.each do |artist| %>
          <li><%= link_to image_tag(artist.image), artist%><%=artist.name%></li>
      <% end %>
    </ul>
  </div>
<!--
  <table class="table table-bordered">
    <thead>
      <tr>
        <th></th>
        <th>Name</th>
        <th>Genre</th>
        <th>Options</th>
      </tr>
    </thead>
    <tbody>
      <% @artists.each do |artist| %>
        <tr>
          <td><%= link_to image_tag(artist.image, width:'25', height:'25'), artist%></td>
          <td><%= link_to artist.name, artist %></td>
          <td><%= artist.genre.name unless artist.genre.nil? %></td>
          <% if artist.user == current_user%>
          <td><%= link_to image_tag("Songs/trash.png", width:'25', height:'25'), artist, method: :delete, data: { confirm: 'Are you sure?' } %>
          <%= link_to image_tag("Songs/edit.svg", width:'20', height:'20'), edit_artist_path(artist) %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
-->

app/views/artists/new.html.erb
<h1>New Artist</h1>

<%= render 'form', artist: @artist %>

<%= link_to 'Back', artists_path %>

app/views/artists/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="bg-faded p-4 my-4">
    <!-- Welcome Message -->
    <div class="left-float">
      <div align="center">
    <%= image_tag(@artist.image, width:'250', height:'250')%>
  </div>

  </div>
  <div class="left-float">
    <div align="left">
        <h6><strong><%= @artist.name %> </strong></h6>
        <p><strong>Description:</strong>
          <%= @artist.description %> </p>
        <p><strong>Genre:</strong>
          <%= link_to @artist.genre.name, @artist.genre unless @artist.genre.nil? %></p>
        <p><strong>Nationality:</strong>
          <%= @artist.nationality %></p>
        <p><strong>Active time:</strong>
          <%= @artist.active_time %></p>
          <% if @artist.user == current_user	  %>
          <%= link_to image_tag("Songs/trash.png", width:'25', height:'25'), @artist, method: :delete, data: { confirm: 'Are you sure?' } %>
          <%= link_to image_tag("Songs/edit.svg", width:'20', height:'20'), edit_artist_path(@artist) %>
          <%end %>
          <%= link_to 'All artists', artists_path %>


    </div>
  </div>
  <div style="clear:both"></div>
  <hr class="divider">





          <h3 class="text-uppercase my-0">Albums:</h3>
            <table class="table table-bordered">
              <thead>
                <tr>
                  <th></th>
                  <th>Title</th>
                  <th>Genre</th>
                  <th colspan="2"></th>
                </tr>
              </thead>

              <tbody>
                <% @albums.each do |album| %>
                  <tr>
                    <div align="right">
                    <td><%= image_tag(album.image, height:'50', width:'50') %></td>
                  </div>
                    <td><%= link_to album.title, album %></td>

                    <td><%= album.genre.name %></td>
                    <td><% if album.user == current_user %>
                    <%= link_to image_tag("Songs/trash.png", width:'25', height:'25'), album, method: :delete, data: { confirm: 'Are you sure?' } %>
                    <%= link_to image_tag("Songs/edit.svg", width:'20', height:'20'), edit_album_path(album) %></td>
                    <% end %>
                  </tr>
                <% end %>
              </tbody>
            </table>


            <hr class="divider">

          <h3 class="text-uppercase my-0">News:</h3>
          <table class="table table-bordered">
            <tbody>
            <% @posts.each do |post| %>
                <tr>
                  <td>
                    <h4><strong>Title: <%= link_to post.title, post %></strong></h4>
                    <h4>Content: <%= post.body %></h4>
                    <h5>Related artist: <%= link_to "#{post.artist.name}", post.artist %></h5>
                    <h5>Created by: <%= link_to "#{post.user.email}", "/users/profile/#{post.user.id}" %></h5>
                    <% if post.user == current_user %>
                        <%= link_to 'Edit', edit_post_path(post) %>
                        <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
                    <% end %>
                  </td>
                </tr>
            <% end %>
            </tbody>
          </table>
    </div>
  </div>