config/routes.rb
Rails.application.routes.draw do
  #get 'favorites/index'

  post '/rate' => 'rater#create', :as => 'rate'
  get 'users/show' => 'users#show'
  get 'users/profile/:id' => 'users#profile'
  resources :favorites
  #get 'users/edit' => 'users#edit'
  #patch 'users/update' => 'users#update'
  resources :genres
  resources :playlists
  resources :albums
  resources :posts
  resources :songs
  resources :artists
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'home_page/Index'

  devise_for :users
  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :artist
  has_many :songs
  belongs_to :user
  belongs_to :genre
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :songs
  has_many :albums
  belongs_to :user
  belongs_to :genre
  #letsrate_rateable "quality"
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :song
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :albums
  has_many :artists
  has_many :songs
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/playlist.rb
class Playlist < ApplicationRecord
  has_many :songs
  belongs_to :user
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :artist
  belongs_to :user
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :album
  belongs_to :artist
  belongs_to :user
  belongs_to :genre
  ratyrate_rateable 'song'
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :artists
  has_many :albums
  has_many :songs
  has_many :posts
  has_many :favorites
  ratyrate_rater
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/controllers/songs_controller.rb
require 'api_consuming'
class SongsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_song, only: [:show, :edit, :update, :destroy, :add_favorite]

  # GET /songs
  # GET /songs.json
  def index
    @favorites = Favorite.where(:user_id => current_user.id)
    if params[:format]
      @songs = Song.where(:genre_id => params[:format])
    else
      @songs = Song.all
    end
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
    @video = api_consum "https://www.youtube.com/results?sp=EgIQAQ%253D%253D&search_query=#{@song.name}+#{@song.artist.name}"
    indice = @video.index('watch?v=')
    @video = @video[indice+8..-1]
    new_index = @video.index('"')
    @video_id = @video[0..new_index-1]
  end

  # GET /songs/new
  def new
    @song = Song.new
  end

  # GET /songs/1/edit
  def edit
  end

  # POST /songs
  # POST /songs.json
  def create
  #  puts 'holas'
  #  puts song_params
 #   puts 'hola'
 #   puts song_params
 #   puts 'hola'
 #   puts song_params[:al]
  #  puts song_params[:ar]
   # puts 'hola'
    song_params2 = {}
    song_params.each do |key, value|
      song_params2[key] = value if key != :genre or key != :artist or key != :album
    end
    song_params2[:genre]= Genre.find(song_params[:genre])
    song_params2[:album]= Album.find(Integer(song_params[:album]))
    song_params2[:artist]= Album.find(Integer(song_params[:album])).artist

    @song = Song.new(song_params2)
    @song.user = current_user
    respond_to do |format|
      if @song.save
        format.html { redirect_to @song, notice: 'Song was successfully created.' }
        format.json { render :show, status: :created, location: @song }
      else
        format.html { render :new }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end
  # PATCH/PUT /songs/1
  # PATCH/PUT /songs/1.json
  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to @song, notice: 'Song was successfully updated.' }
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy

    @song.destroy
    respond_to do |format|
      format.html { redirect_to songs_url, notice: 'Song was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def add_favorite
    Favorite.create user_id: current_user.id, song_id: @song.id
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def song_params
      params.require(:song).permit(:name, :lyrics, :duration, :genre, :artist, :album, :image)
    end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/home_page_helper.rb
module HomePageHelper
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/songs/_form.html.erb
<%= form_with(model: song, local: true) do |form| %>
  <% if song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
      <% song.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :song_name %>
  </div>

  <div class="field">
    <%= form.label :lyrics %>
    <%= form.text_area :lyrics, id: :song_lyrics %>
  </div>



  <div class="field">
    <%= form.label :genre %>
    <%= form.collection_select :genre, Genre.order(:name),:id,:name, include_blank: true %>
  </div>

  <div class="field">
    <%= form.label :album %>
    <%= form.collection_select :album, Album.order(:title),:id,:title, include_blank: true %>  <%= link_to 'New Album', new_album_path %>
  </div>
    <div class="field">
      <%= form.label :image %>
      <%= form.file_field :image %>
    </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/songs/edit.html.erb
<h1>Editing Song</h1>

<%= render 'form', song: @song %>

<%= link_to 'Show', @song %> |
<%= link_to 'Back', songs_path %>

app/views/songs/index.html.erb
<p id="notice"><%= notice %></p>


<div class="container">
  <div class="bg-faded p-4 my-4">
    <!-- Welcome Message -->
    <div class="text-center mt-4">
      <h1 class="my-2">Songs <%= image_tag('Songs/img1.png', height:'52', width:'52') %></h1>
        <hr class="divider">
        <h2 class="text-center text-lg text-uppercase my-0">If you want, you can:
        <strong><%= link_to 'Create Song', new_song_path %></strong>
        </h2>
      </div>
    </div>
  </div>
  <hr class="divider">
  <h2 class="text-center text-lg text-uppercase my-0">Or
  <strong>Explore</strong>
  </h2>
  <hr class="divider">


<div class = 'container'>

  <table class="table table-bordered">
      <thead>
        <tr>
          <th></th>
          <th>Name</th>
          <th>Artist</th>
          <th>Album</th>
          <th>Genre</th>
          <th colspan="3"></th>
        </tr>
      </thead>


      <tbody>
        <% @songs.each do |song| %>
          <tr>

            <% begin %>
            <% @favorite = @favorites.find_by(song_id: song.id) %>
            <% if @favorite.user_id == current_user.id %>
              <td><%= link_to image_tag("Songs/tick.png", width:'25', height:'25'), @favorite, method: :delete%></td>
            <% else %>
            <td><%= link_to image_tag("Songs/plus.png", width:'25', height:'25'), new_favorite_path(song) %></td>
            <% end %>
            <%rescue ActiveRecord::RecordNotFound, NoMethodError %>
            <td><%= link_to image_tag("Songs/plus.png", width:'25', height:'25'), new_favorite_path(song) %></td>
            <% end %>
            <td><%= link_to song.name, song %></td>
            <td><%= link_to "#{song.artist.name}", song.artist %></td>
            <td><%= link_to "#{song.album.title}", song.album %></td>
            <td><%= link_to song.genre.name, song.genre %></td>
            <% if song.user == current_user %>
            <td><%= link_to image_tag("Songs/trash.png", width:'25', height:'25'), song, method: :delete, data: { confirm: 'Are you sure?' } %>
            <%= link_to image_tag("Songs/edit.svg", width:'20', height:'20'), edit_song_path(song) %></td>
            <% end %>
            <td> <%=	 rating_for song, 'song', disable_after_rate: true  %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
</div>

app/views/songs/new.html.erb
<h1>New Song</h1>

<%= render 'form', song: @song %>

<%= link_to 'Back', songs_path %>

app/views/songs/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">

  <div class="bg-faded p-4 my-4">
    <div class="left-float">
      <div align="center">
    <%= image_tag(@song.album.image, width:'250', height:'250') %>
  </div>

  </div>
  <div class="left-float">
    <div align="left">
        <h6><strong>  <%= @song.name %> </strong></h6>
        <p><strong>  Genre:</strong>
          <%= link_to  @song.genre.name, @song.genre unless @song.genre.nil? %></p>
        <p><strong>  Album:</strong>
          <%= link_to "#{@song.album.title}", @song.album unless @song.album.nil?%></p>
        <p><strong>Artist:</strong>
          <%= link_to "#{@song.artist.name}", @song.artist unless @song.artist.nil?%></p>
          <% if @song.user == current_user	 %>
          <%= link_to image_tag("Songs/trash.png", width:'25', height:'25'), @song, method: :delete, data: { confirm: 'Are you sure?' } %>
          <%= link_to image_tag("Songs/edit.svg", width:'20', height:'20'), edit_song_path(@song) %>
          <%end	%>
          <%= link_to 'All songs', songs_path %>
    </div>
  </div>
  <div style="clear:both"></div>
  <hr class="divider">
 </div>
</div>
<div class="container">
 <div class="bg-faded p-4 my-4">
   <div align="center">
     <h1>Player:</h1>
    <iframe id="player" type="text/html" width="640" height="360" frameborder='0'
            src=<%="http://www.youtube.com/embed/#{@video_id}?enablejsapi=1&origin=#{song_url(@song)}"%>
    ></iframe>
  </div>
  </div>
</div>

</div>