config/routes.rb
Rails.application.routes.draw do
  #get 'favorites/index'

  post '/rate' => 'rater#create', :as => 'rate'
  get 'users/show' => 'users#show'
  get 'users/profile/:id' => 'users#profile'
  resources :favorites
  #get 'users/edit' => 'users#edit'
  #patch 'users/update' => 'users#update'
  resources :genres
  resources :playlists
  resources :albums
  resources :posts
  resources :songs
  resources :artists
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'home_page/Index'

  devise_for :users
  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :artist
  has_many :songs
  belongs_to :user
  belongs_to :genre
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :songs
  has_many :albums
  belongs_to :user
  belongs_to :genre
  #letsrate_rateable "quality"
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :song
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :albums
  has_many :artists
  has_many :songs
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/playlist.rb
class Playlist < ApplicationRecord
  has_many :songs
  belongs_to :user
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :artist
  belongs_to :user
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :album
  belongs_to :artist
  belongs_to :user
  belongs_to :genre
  ratyrate_rateable 'song'
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :artists
  has_many :albums
  has_many :songs
  has_many :posts
  has_many :favorites
  ratyrate_rater
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :artist_id, :image)
    end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/home_page_helper.rb
module HomePageHelper
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :post_title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :post_body %>
  </div>

  <div class="field">
    <%= form.label :artist_id %>
    <%= form.collection_select :artist_id, Artist.order(:name),:id,:name, include_blank: true  %> <%= link_to 'New Artist', new_artist_path %>
  </div>
    <div class="field">
      <%= form.label :image %>
      <%= form.file_field :image %>
    </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="bg-faded p-4 my-4">
    <!-- Welcome Message -->
    <div class="text-center mt-4">
      <h1 class="my-2">News <%= image_tag('News/img2.png', height:'72', width:'72')%></h1>
        <hr class="divider">
        <h2 class="text-center text-lg text-uppercase my-0">If you want, you can:
        <strong><%= link_to 'New Post', new_post_path %></strong>
        </h2>
      </div>
    </div>
  </div>
  <hr class="divider">
  <h2 class="text-center text-lg text-uppercase my-0">Or
  <strong>Explore</strong>
  </h2>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th><h2>News</h2></th>
      </tr>
    </thead>

    <tbody>
      <% @posts.each do |post| %>
        <tr>
          <td>
            <h4><strong>Title: <%= link_to post.title, post %></strong></h4>
            <h4>Content: <%= post.body %></h4>
            <h5>Related artist: <%= link_to "#{post.artist.name}", post.artist %></h5>
            <h5>Created by:<%= link_to "#{post.user.email}", "/users/profile/#{post.user.id}"  %></h5>
            <% if post.user == current_user %>
              <%= link_to image_tag("Songs/edit.svg", width:'20', height:'20'), edit_post_path(post) %>
              <%= link_to image_tag("Songs/trash.png", width:'25', height:'25'), post, method: :delete, data: { confirm: 'Are you sure?' } %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="bg-faded p-4 my-4">
    <!-- Welcome Message -->
    <div class="text-center mt-4">
      <h1 class="my-2"> Title: <%= @post.title %></h1>
      <% if @post.user == current_user %>
      <%= link_to 'Edit', edit_post_path(@post)  %> |
      <%end  %>
      <%= link_to 'All posts', posts_path %>
      <hr class="divider">
    </div>
        <p> <%= @post.body %></p>
        <p>
          <h5>Related artist: <%= link_to "#{@post.artist.name}", @post.artist %></h5>
          <h5>Created by: <%= link_to "#{@post.user.email}", "/users/profile/#{@post.user.id}" %></h5>
          <hr class="divider">
    </div>
  </div>